#name: BE_184623
services:
  prestashop:
    #use local image TODO: change to dockerhub image when pipeline is ready
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash", "-c", "/tmp/docker_run.sh"]
    ports:
      - 18462:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_184623
      DB_USER: root
      DB_PASSWD: student
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
      PS_ERASE_DB: 1
      PS_INSTALL_DB: 1
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:18462
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s
    networks:
      - admin-mysql_default
      - BE_18462_prestashop_network
  memcached:
    image: memcached:1.6-alpine
    container_name: BE_184623_memcached
    command: 
      -vv
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          cpus: '0.25'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s
    networks:
      - BE_18462_prestashop_network

networks:
  BE_18462_prestashop_network:
  admin-mysql_default:
    external: true